<? include ("http://www.vallisbook.org/layout/header.php"); ?> 
<!-- ****************************************************************************************** -->

<h1>Review</h1>

<!-- <div id="review-menu"><a href="schneider.php">next review >></a></div> -->

<p><b>Review from Quarterly Journal of the Royal Meteorological Society<br>by Peter L. Read, University of Oxford</b> (<a href="http://www.atm.ox.ac.uk/user/read/" target="_blank">homepage</a>)</p>

<p>appeared in <a href="http://www3.interscience.wiley.com/cgi-bin/abstract/117869217/ABSTRACT" target="_blank">Quarterly Journal of the Royal Meteorological Society</a> in October 2007 (<a href="read.pdf", target="_blank">Review as PDF</a>)</p>

<p>Fluid dynamics underlies much of our understanding of both the atmosphere and the oceans, from the smallest eddies and gusts of wind to the scale of the planet itself. Despite being a long-established branch of classical physics, however, the subject of fluid dynamics continues to make rapid and vigorous advances, invigorated from time to time by contact with other branches of physics and other disciplines. This presents a considerable challenge to both new students and established researchers alike, compounded by a comparative dearth of clear and authoritative textbooks that deal with the subject at a serious professional and pedagogical level. Recent research has also stimulated an increasing awareness of shared issues and scientific questions between the atmospheric and oceanic communities, who have been historically and culturally isolated from each other, though ‘divided by a common language’, with shared terms such as ‘baroclinic’ or ‘barotropic’ that have subtly different interpretations. It is welcome and refreshing, therefore, to see a leading researcher and educator with a foot in both ‘camps’ adopting a unified approach to the fundamental principles of both atmospheric and oceanic dynamics.</p> 

<p>Geoffrey Vallis’s book is conceived on an impressive scale, covering both the fundamental dynamical theory of rotating stratified fluids, instabilities, wave–mean fow interactions and turbulence, and applications to modelling and understanding the large-scale circulations of the atmosphere and oceans, all within a single volume. The book is organized into four main sections: Fundamentals of geophysical fuid dynamics; instabilities, wave–mean fow interaction and turbulence; large-scale atmospheric circulation; and large-scale oceanic circulation. The material in each section is well organized and logically presented, with clear illustrations and worked examples, and interesting and challenging sets of problems at the end of each chapter, together with a dynamic website intended to provide supplementary material, solutions to problems for instructors and other background information. 
The approach is generally quite mathematical (at least from the viewpoint of a physicist, though still accessible), starting from first principles almost throughout, in which each topic is treated with meticulous thoroughness. As Vallis himself asserts, at least the early parts of the book are actually a treatise in ‘geophysical fuid dynamics’ (GFD) – a term first coined in the 1950s originally to mean the fluid dynamical fundamentals underlying meteorology and oceanography, and even adopted by Joseph Smagorinsky, the founder of NOAA’s atmospheric modelling research group in Princeton, into the title of the laboratory in 1963. More recently, however, this term has been widened to include the dynamics of volcanoes, magma fows, planetary interiors and even space plasmas. Speaking as a GFD practitioner, it is somewhat disappointing that Vallis himself evidently regards ‘GFD’ as a subject that is rather austere, theoretical and ‘dry’ – the latter quality he regards as ‘best reserved for martinis and humour’ – that demands an ascetic approach reminiscent of monastic discipline! Yet he himself has clearly devoted enormous intellectual energy, enthusiasm and insights into his expositions of basic processes in atmospheric and oceanic dynamics.</p>
 
<p>His discussion of potential vorticity, for example, is full of insight and clarity, covering both kinematical and geometrical aspects. The chapters on instabilities and wave–mean flow interactions are masterly in the clarity of their presentation and are very comprehensive. The book also deals nicely with the principles underlying the parametrization of eddy transports – vital for modern ocean models and being rediscovered in the context of atmospheric science. The only areas where I felt I began to part company with him was in some aspects of his discussion of geostrophic turbulence, where his assertion of the ‘Rhines barrier’ to upscale energy cascades does not quite reflect some of the most modern thinking in this area. But this is a small issue in what is otherwise an impressive and comprehensive treatment.</p>
 
<p>The only somewhat negative aspect that struck me on reading this book is that it presents relatively little in the way of real observations of the atmosphere or oceans, or even illustrative laboratory experiments with which to compare against the elegant theoretical results expounded at length throughout the book. This tends to convey an impression of the subject that is disconcertingly precise and ‘tidy’ – free of any hint of the ‘suffocating detail of the real world’. To include this extra dimension in the present book would, of course, add substantially to what is already a very weighty tome. But this dimension could perhaps eventually be added via the book’s website (http://www.vallisbook.org/)? The latter is certainly highly commendable as a potentially valuable (and easily updated) resource, though it is as yet somewhat underdeveloped, containing to date only copies of the book’s illustrations, together with a set of errata, a few internet links and solutions to some of the problems. It is slightly surprising to see so few of the problems with solutions offered (with appeals to readers to provide additional solutions), leading one to wonder how many of the problems have actually been through the fiery trials of student experience.</p>
 
<p>As stated in the preface, the book is intended to be accessible to beginning graduate students, while also serving as an introduction to scientists in other fields and as a reference for atmosphere–ocean professionals. In these aims it is clearly very successful, and is sure to grace the shelves of libraries and (at CUP’s remarkably reasonable price for such a large hardback volume) even individuals for many years to come, both as a reference and a tutorial text.</p> 

<!-- ****************************************************************************************** -->
<? include("http://www.vallisbook.org/layout/footer.php"); ?>
